profile: dev
models: 
  - model: gpt-4o
    api_type: azure      
    api_version: 2024-08-01-preview
logging: 
  root_log_level: debug
  log_level: debug
chat_history:  
  database_type: sqlite # cosmos or sqlite
  database_path: tmp/high_level_logs.db # only used for sqlite
  database_name: ToDoList # only used for cosmos
  memory_path: tmp
chat_service:
  type: multi_agent
tool_service:
  enable: false
azure_search_services:
  - service: default    
    endpoint: https://search-demo-eli.search.windows.net
web_configuration:
  type: fastapi #currently only fastapi is supported
  ip_address: "0.0.0.0"
  port: 80
  authentication: 
    enable: false # true or false
    type: basic # basic     